<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="MassTransit" Version="9.0.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.16.1" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Common.Application">
      <HintPath>..\Common.Application\bin\Debug\net9.0\Common.Application.dll</HintPath>
    </Reference>
    <Reference Include="Common.Domain">
      <HintPath>..\Common.Domain\bin\Debug\net9.0\Common.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
