<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Infrastructure\Common.Infrastructure.csproj" />
    <ProjectReference Include="..\PCL.Modules.Evidence.Application\PCL.Modules.Evidence.Application.csproj" />
    <ProjectReference Include="..\PCL.Modules.Evidence.Presentation\PCL.Modules.Evidence.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\Migrations\" />
  </ItemGroup>

</Project>
