// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PCL.Modules.Evidence.Infrastructure.Database;

#nullable disable

namespace PCL.Modules.Evidence.Infrastructure.Database.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    [Migration("20260712054118_AddReliableEvidenceUploadLifecycle")]
    partial class AddReliableEvidenceUploadLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("evidence")
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "evidence");
                });

            modelBuilder.Entity("Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("OutboxMessageId", "Name");

                    b.ToTable("outbox_message_consumers", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFile", b =>
                {
                    b.Property<Guid>("EvidenceItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumAlgorithm")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChecksumValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CleanupAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CleanupNextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("PhysicalDeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadAttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VersionId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("EvidenceItemId");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("StorageProfileId");

                    b.HasIndex("UploadAttemptId")
                        .IsUnique();

                    b.HasIndex("UploadStatus", "UploadExpiresAt");

                    b.ToTable("evidence_file", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_evidence_file_FileSizeBytes", "\"FileSizeBytes\" > 0 AND \"FileSizeBytes\" <= 26214400");
                        });
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFileInitialization", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvidenceItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OwnerId", "IdempotencyKey");

                    b.HasIndex("EvidenceItemId")
                        .IsUnique();

                    b.ToTable("evidence_file_initialization", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFileUploadAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CleanupAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CleanupNextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvidenceItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("PhysicalDeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceItemId");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("StorageProfileId");

                    b.HasIndex("StatusChangedAt", "PhysicalDeletedAt");

                    b.ToTable("evidence_file_upload_attempt", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemovalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RemovedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "OwnerId");

                    b.ToTable("evidence_item", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.EvidenceStorageSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActiveStorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveStorageProfileId");

                    b.ToTable("evidence_storage_settings", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_evidence_storage_settings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.LocalStorageProfileConfiguration", b =>
                {
                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("StorageProfileId");

                    b.ToTable("local_storage_profile_configuration", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.S3StorageProfileConfiguration", b =>
                {
                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("KeyPrefix")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("StorageProfileId");

                    b.ToTable("s3_storage_profile_configuration", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.StorageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProviderType");

                    b.ToTable("storage_profile", "evidence");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFile", b =>
                {
                    b.HasOne("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceItem", null)
                        .WithOne("File")
                        .HasForeignKey("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFile", "EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCL.Modules.Evidence.Domain.Storage.StorageProfile", null)
                        .WithMany()
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFileInitialization", b =>
                {
                    b.HasOne("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceItem", null)
                        .WithOne()
                        .HasForeignKey("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFileInitialization", "EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceFileUploadAttempt", b =>
                {
                    b.HasOne("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceItem", null)
                        .WithMany()
                        .HasForeignKey("EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCL.Modules.Evidence.Domain.Storage.StorageProfile", null)
                        .WithMany()
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.EvidenceStorageSettings", b =>
                {
                    b.HasOne("PCL.Modules.Evidence.Domain.Storage.StorageProfile", null)
                        .WithMany()
                        .HasForeignKey("ActiveStorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.LocalStorageProfileConfiguration", b =>
                {
                    b.HasOne("PCL.Modules.Evidence.Domain.Storage.StorageProfile", null)
                        .WithOne("LocalConfiguration")
                        .HasForeignKey("PCL.Modules.Evidence.Domain.Storage.LocalStorageProfileConfiguration", "StorageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.S3StorageProfileConfiguration", b =>
                {
                    b.HasOne("PCL.Modules.Evidence.Domain.Storage.StorageProfile", null)
                        .WithOne("S3Configuration")
                        .HasForeignKey("PCL.Modules.Evidence.Domain.Storage.S3StorageProfileConfiguration", "StorageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.EvidenceItems.EvidenceItem", b =>
                {
                    b.Navigation("File");
                });

            modelBuilder.Entity("PCL.Modules.Evidence.Domain.Storage.StorageProfile", b =>
                {
                    b.Navigation("LocalConfiguration");

                    b.Navigation("S3Configuration");
                });
#pragma warning restore 612, 618
        }
    }
}
